modLoader = "javafml"
loaderVersion = "${loaderVersionRange}"
license = "MIT"
#issueTrackerURL="https://github.com/TonimatasDEV/RecipeFixer/issues"

[[mods]]
modId = "recipefixer"
version = "${modVersion}"
displayName = "Recipe Fixer"
#updateJSONURL="modrinth"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="itemstackemptyfix.png"
credits="Mysticpasta1 - Founder and primary developer | TonimatasDEV - Publisher"
authors = "Mysticpasta1, TonimatasDEV"

description = '''
Simple mod to
'''

[[mixins]]
config = "recipefixer.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.recipefixer]]
modId = "neoforge"
type = "required"
versionRange = "${neoVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.recipefixer]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"

#[features.recipefixer]
#openGLVersion="[3.2,)"
